/* assignments.js — a signed-in student's own assignments (item S6/E4
 * follow-up)
 *
 * Same shape as invites.js/entitlements.js/billing.js: small, injectable
 * dependencies, never throws, every failure resolves to an explicit
 * `{ ok: false, error }`.
 *
 * Every field name is copied from reading alcoiaServer directly, not
 * inferred:
 *   GET /api/assignments/mine -> { assignments: [{ assignmentId, classId,
 *     className, closesAt, documents: [{ documentId, format, status }] }] }
 *     (src/http/routes/assignments.js — a NEW route, added by this item;
 *     confirmed there was no student-facing assignment listing anywhere
 *     before it by exhaustively grepping every registered route first)
 *   GET /api/documents/:id/download-url -> { url, expiresInSeconds }
 *     (src/http/routes/documents.js — pre-existing, unmodified)
 *
 * There is NO assignment title anywhere in the server's schema — confirmed
 * by reading migrations/*_create-assignments.sql directly, not assumed.
 * className is the only real, confirmed identifying text this response
 * carries; callers should display that, not invent a title.
 */

export function createAssignmentsManager(opts = {}) {
  const fetchImpl = opts.fetchImpl || (typeof fetch !== 'undefined' ? fetch : null);
  const getSession = opts.getSession;
  const mineUrl = opts.mineUrl;
  const documentsUrl = opts.documentsUrl;

  function authHeaders(token) {
    return { Authorization: `Bearer ${token}` };
  }

  /* Returns { ok: true, assignments } or { ok: false, error }. Every
   * assignment's `documents` array is passed through verbatim — zero,
   * one, or more entries (there is no uniqueness constraint on an
   * assignment's document, confirmed by reading the server's own
   * migration) — never assumed to be exactly one. */
  async function listMine() {
    const session = await getSession();
    if (!session || typeof session.token !== 'string' || !session.token) {
      return { ok: false, error: 'no_session' };
    }
    if (!mineUrl || !fetchImpl) return { ok: false, error: 'no_mine_url' };

    try {
      const resp = await fetchImpl(mineUrl, { method: 'GET', headers: authHeaders(session.token) });
      const data = await resp.json().catch(() => null);
      if (!resp.ok) {
        return { ok: false, error: (data && typeof data.error === 'string' && data.error) || `status_${resp.status}` };
      }
      if (!data || !Array.isArray(data.assignments)) {
        return { ok: false, error: 'malformed_response' };
      }
      const assignments = [];
      for (const a of data.assignments) {
        if (!a || typeof a.assignmentId !== 'string' || !a.assignmentId
          || typeof a.classId !== 'string' || !a.classId
          || typeof a.closesAt !== 'string' || !Array.isArray(a.documents)) {
          return { ok: false, error: 'malformed_response' };
        }
        assignments.push({
          assignmentId: a.assignmentId,
          classId: a.classId,
          className: typeof a.className === 'string' ? a.className : null,
          closesAt: a.closesAt,
          documents: a.documents
            .filter((d) => d && typeof d.documentId === 'string' && typeof d.format === 'string' && typeof d.status === 'string')
            .map((d) => ({ documentId: d.documentId, format: d.format, status: d.status })),
        });
      }
      return { ok: true, assignments };
    } catch (e) {
      return { ok: false, error: 'network_error' };
    }
  }

  /* Returns { ok: true, url, expiresInSeconds } or { ok: false, error }.
   * A fresh signed URL is generated by the server on every call — never
   * cached across calls here, matching CLAUDE.md's own "never a bare
   * redirect" framing for how this route is documented server-side. */
  async function getDownloadUrl(documentId) {
    const id = String(documentId || '').trim();
    if (!id) return { ok: false, error: 'no_document_id' };
    const session = await getSession();
    if (!session || typeof session.token !== 'string' || !session.token) {
      return { ok: false, error: 'no_session' };
    }
    if (!documentsUrl || !fetchImpl) return { ok: false, error: 'no_documents_url' };

    try {
      const resp = await fetchImpl(`${documentsUrl}/${encodeURIComponent(id)}/download-url`, {
        method: 'GET',
        headers: authHeaders(session.token),
      });
      const data = await resp.json().catch(() => null);
      if (!resp.ok) {
        return { ok: false, error: (data && typeof data.error === 'string' && data.error) || `status_${resp.status}` };
      }
      if (!data || typeof data.url !== 'string' || !data.url) {
        return { ok: false, error: 'malformed_response' };
      }
      return { ok: true, url: data.url, expiresInSeconds: typeof data.expiresInSeconds === 'number' ? data.expiresInSeconds : null };
    } catch (e) {
      return { ok: false, error: 'network_error' };
    }
  }

  return { listMine, getDownloadUrl };
}
