/* knowledge-unit.js — V1 content-based knowledge-unit identity
 *
 * Replaces the fragile `text.slice(0, 80).trim()` identity used throughout
 * this codebase (host.js's paragraphKey computations, session-recall.js,
 * epistemic-engine.js's "concept" argument) with a deliberate, deterministic
 * hash of the paragraph's own NORMALIZED content — stable across reload,
 * across a fresh DOM scan, and across a paragraph moving to a different
 * position in the document, as long as its own text is unchanged.
 *
 * WHAT THIS IS NOT, stated plainly per this item's own scope boundary: not a
 * semantic concept, not a knowledge graph node, not cross-document. It is a
 * content-unit identity, document-scoped by whatever context wraps it
 * (assignment_id server-side, documentKey client-side) — exactly the same
 * way paragraphKey and paragraph_index are already document-scoped today,
 * not by anything baked into this string itself. Two unrelated documents
 * that happen to share a sentence get the same knowledgeUnitId for that
 * sentence; nothing here claims that's meaningful across documents, and
 * nothing downstream in this step reads it that way.
 *
 * ALGORITHM: FNV-1a over the normalized text, with the (pre-normalization
 * input, post-normalization length) folded in — deliberately mirroring
 * receipt.js's own hashUrl(), the one hash this codebase already has for
 * exactly this class of problem ("a stable identifier, not a security
 * control"). Not SHA-256/crypto.subtle, and that is a deliberate choice,
 * not an oversight:
 *   - crypto.subtle is unavailable in an INSECURE-context content script
 *     (a plain http:// page) — this extension runs on arbitrary web pages,
 *     not only https ones, so a Web Crypto dependency would silently stop
 *     working on some fraction of the pages this product exists to read.
 *   - crypto.subtle.digest is async-only. The real computation sites for
 *     this identity (host.js, replacing today's synchronous
 *     text.slice(0,80).trim() calls) sit inside already-hot,
 *     frequently-called paths; several already became async in the prior
 *     step (pickLevel(), for the quiz-evidence storage read) but making
 *     EVERY paragraphKey-adjacent computation async as well — including
 *     ones that don't need to be — is exactly the kind of broader rewrite
 *     this step's own brief says not to perform.
 * A 32-bit FNV-1a hash gives ~4 billion buckets; for the handful to low
 * hundreds of distinct paragraphs a single document realistically has, the
 * collision probability is negligible, and every consumer treats this as an
 * identifier to be matched for equality, never as a security or uniqueness
 * guarantee — the same posture hashUrl() already takes.
 *
 * NORMALIZATION RULES, exactly, and only:
 *   1. Coerce to a string (`String(text ?? '')`).
 *   2. Collapse every run of Unicode whitespace (spaces, tabs, newlines,
 *      non-breaking spaces, etc. — \s already covers these in a JS regex)
 *      to a single ASCII space. This is the one thing "the same paragraph"
 *      can legitimately look different as: how a page's own markup happens
 *      to wrap or indent text, or whether extraction picked up a line break
 *      mid-sentence, changes nothing a reader would consider the content.
 *   3. Trim leading/trailing whitespace.
 * That is the entire rule set. Deliberately NOT done, because the
 * investigation for this item found no evidence the existing extraction
 * pipeline needs it for identity purposes (text-difficulty.js's own
 * toLowerCase() calls are for word-frequency lookups against a fixed
 * word list, a different and narrower purpose than paragraph identity):
 *   - No case folding. "Paris" and "paris" hash differently, on purpose.
 *   - No punctuation stripping, no diacritic stripping, no word-content
 *     changes of any kind. A meaningful edit to the paragraph — even one
 *     word — MUST produce a different identity; this module never decides
 *     that two genuinely different sentences are "close enough."
 *
 * EMPTY/INVALID INPUT: normalized-empty text (nothing, or whitespace-only)
 * has no content to identify, so this returns `null` rather than hashing an
 * empty string into a value that would look like a real identity. Every
 * caller already treats "no identity available" as a valid, common case
 * (paragraphKey and paragraph_index both already tolerate `null` this way).
 *
 * DUPLICATE CONTENT, stated explicitly per this item's own requirement:
 * this hashes CONTENT, not OCCURRENCE. Two physically distinct paragraphs
 * in the same document with byte-for-byte-after-normalization identical
 * text produce the SAME knowledgeUnitId — correctly, since as a knowledge
 * unit they genuinely are the same thing to have read and be asked about.
 * paragraphIndex (unchanged, still generated by paragraph-tracker.js) is
 * what still distinguishes WHICH occurrence a reader is currently at, for
 * ordering/navigation/UI purposes — knowledgeUnitId was never meant to,
 * and does not, replace it for that.
 */

const FNV_OFFSET_BASIS = 0x811c9dc5;
const FNV_PRIME = 0x01000193;

/* Collapses all whitespace runs to a single space and trims the ends. See
 * this file's own header for exactly what this does and does not do. */
export function normalizeParagraphText(text) {
  return String(text ?? '').replace(/\s+/g, ' ').trim();
}

/* FNV-1a, byte-per-UTF-16-code-unit — identical algorithm to receipt.js's
 * hashUrl(), factored out here rather than imported from that file: that
 * module is popup-page-only (never loaded by the content-script bundle
 * this runs in) and importing across that boundary would be a new, real
 * coupling for two lines of arithmetic neither file's own header currently
 * has a reason to justify. */
function fnv1a(s) {
  let h = FNV_OFFSET_BASIS;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, FNV_PRIME) >>> 0;
  }
  return h;
}

/* The V1 knowledge-unit identity. Returns a string, or `null` when there is
 * genuinely no content to identify (see this file's own header). Prefixed
 * `k` (knowledgeUnit) so a value is recognizable as one of this module's
 * outputs at a glance, matching hashUrl()'s own `u` prefix convention —
 * length is folded into the string too, for the identical reason hashUrl()
 * does it: two different-length inputs that happened to collide on the raw
 * FNV-1a output alone are far less likely to also share a length. */
export function computeKnowledgeUnitId(text) {
  const normalized = normalizeParagraphText(text);
  if (!normalized) return null;
  const hash = fnv1a(normalized);
  return `k${hash.toString(16)}${normalized.length.toString(16)}`;
}
